package CORBADLMS;

/**
* CORBADLMS/LibraryMethodsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryInterface.idl
* Thursday, March 7, 2019 at 12:06:37 AM Eastern Standard Time
*/

public final class LibraryMethodsHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBADLMS.LibraryMethods value = null;

  public LibraryMethodsHolder ()
  {
  }

  public LibraryMethodsHolder (CORBADLMS.LibraryMethods initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBADLMS.LibraryMethodsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBADLMS.LibraryMethodsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBADLMS.LibraryMethodsHelper.type ();
  }

}
